with-expecter: true
packages:
  github.com/openmfp/golang-commons/fga/store:
    config:
      dir: fga/store/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper
  github.com/openmfp/golang-commons/policy_services:
    config:
      dir: fga/policy_services/mocks
      outpkg: mocks
    interfaces:
      TenantIdReader:
        config:
          mockname: TenantIdReader
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: directive/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient