version = 1
SPDX-PackageName = "golang-commons"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/golang-commons"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and openMFP contributors and golang-commons contributors."
SPDX-License-Identifier = "Apache-2.0"
