name: "Update License Metadata"

on:
  push:
    # branches: [ "main" ]
  schedule:
    - cron: '32 16 * * 0'

jobs:
  license:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/job-license-metadata.yml@feat/license-generation
    secrets: inherit