name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    uses: openmfp/gha/.github/workflows/pipeline-golang-module.yml@main
    secrets: inherit

